#!/usr/bin/env python

from PySide import QtCore, QtGui, QtUiTools
import requests


def list_latest(limit=10):
    url = 'http://doomworld.com/idgames/api/api.php?action=latestfiles&limit={}&out=json'.format(limit)
    r = requests.get(url)
    return r.json()


class Window(QtGui.QWidget):
    def __init__(self):
        super(Window, self).__init__()

        self.sourceView = QtGui.QTreeView()
        self.sourceView.setRootIsDecorated(False)
        self.sourceView.setAlternatingRowColors(True)
        self.sourceView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)

        mainLayout = QtGui.QVBoxLayout()
        mainLayout.addWidget(self.sourceView)
        self.setLayout(mainLayout)

        self.setWindowTitle("Doomworld wad browser")
        #self.resize(500,600)

        self.sourceModel = QtGui.QStandardItemModel(0, 3, self)
        self.sourceModel.setHeaderData(0, QtCore.Qt.Horizontal, "Name")
        self.sourceModel.setHeaderData(1, QtCore.Qt.Horizontal, "Author")
        self.sourceModel.setHeaderData(2, QtCore.Qt.Horizontal, "Date")
        self.sourceView.setModel(self.sourceModel)

        data = list_latest()
        for row in data['content']['file']:
            self.addRow(row['title'], row['author'], row['rating'])

    def addRow(self, name, author, rating):
        model = self.sourceModel
        model.insertRow(0)
        model.setData(model.index(0, 0), name)
        model.setData(model.index(0, 1), author)
        model.setData(model.index(0, 2), rating)


if __name__=='__main__':
    import sys
    app = QtGui.QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())

